### PR TITLE
Changed up discord.js starter

### PR DESCRIPTION
**Pull request by Korabi-dev**
I added prefixes to commands, and made it, so it makes the content lowercase when checking for commands so if a user says "!pInG” it is still going to work.

### CODE REVIEW

**Comment by Korabi-dev** [comment]
Apologies if There's any bad code :)

**Comment by Milo123459** [comment]
-1. Slash commands are being normalised and if anything this starter should move to using slash commands. Also the command handling in this will only work if you do !ping, but if you do !ping hi it won't work.

**Comment by Korabi-dev** [comment]
> nds are being normalised and if anything this starter should move to using slash commands. Also the command handling in this will only work if you do !ping, but if you do !ping hi it won't work.

I did think of that but also thought it wouldn't be accepted for reasons, ill see on making it slash command friendly :)

**Comment by Korabi-dev** [comment]
Making a new rp

**Pull request closed without merging**
