### PR TITLE
add Vubuntu starter

### PR DESCRIPTION
**Pull request by vital987**
Refer [README](https://github.com/vital987/vubuntu/blob/master/README.md) for more info.

### CODE REVIEW

**Review by PantheraRed — COMMENTED** [review]
- Why should this pull request be merged?
- Why does this pull request only have two files?
- Is this based on your personal project?

**Comment by vital987** [comment]
* Vubuntu was created for free PaaS services like Railway & Heroku where one can get nearly same benefits as of paid VM instances. This project is useful for the ones who want to work on linux & can't afford to install on their local PC, also considering them who dosen't have a PC.
* I made the PR like code-server but if you like the project I will make another PR with all files.
* Yes, this in my personal project, but I can manage it cause it dosen't need much updates, next update will be when ubuntu's next LTS release is launched. In case if some bugs are discovered then I can fix it ASAP.
* **[ * ]** If you are merging the PR then tell me before merging it so I can make some additional changes in my repo.

**Comment by PantheraRed** [comment]
> - Vubuntu was created for free PaaS services like Railway & Heroku where one can get nearly same benefits as of paid VM instances. This project is useful for the ones who want to work on linux & can't afford to install on their local PC, also considering them who dosen't have a PC.

I like the idea. :+1:

**Comment by vital987** [comment]
So how should I apply for the starter?, please tell me step by step.
I will make some changes and then will follow applying steps.

**Comment by vital987** [comment]
* How should I apply for the starter?
* The project is ready for deployment.
* Bug(**not sure**): I deployed new version on Railway and it's still showing me old version regardless how many different projects I create.
    * [This](https://imgur.com/ZI9it5P.png) is the menu from the newly deployed version on GCP CloudShell.
    * [This](https://i.imgur.com/s0PCj2G.png) is the menu from railway deployment, I've replaced G-Edit with Pluma in the new version.
    * Also VS code was not working in the old version, and it is working in GCP but not in Railway.
    * What is actually happening: Railway is deploying the projects from the previous downloaded docker images, and I can gurantee that cause the new deployments are not taking a minute to deploy, they are going instantly into the running state while atleast 2 to 3 mins were required to download and deploy the project.
    * Why is this happening for newly created deployments?This also happened when I deleted my old deployment and created new one.
    * Does Railway cache docker images and use it for different projects requesting same image to prevent more bandwidth usage or something?

**Review by JakeCooper — COMMENTED** [review]
VNCs are prohibited on Railway as per our ToS

You’ll want to remove the button + any deployments you’ve got or we’ll move to a full ban

**Comment by PantheraRed** [comment]
Oh well. Maybe I should read the ToS carefully. My apologies for the review. :+1:

**Comment by vital987** [comment]
Sure😕

**Pull request closed without merging**
